# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[

  # deps for tests/swifttest
  {
    goPackagePath = "github.com/ncw/swift";
    fetch = {
      type = "git";
      url = "https://github.com/ncw/swift";
      rev = "ba19fe35e796969e50f19bd748a770ec5d191ece";
      sha256 = "0zjm7xibyjisdkvj6fm95hhyh61rf9v85nasd4qlyqi4f935rg15";
    };
  }

  # deps for tests/clone
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "3744606dbb67b99c60d3f11cb10bd3f9e6dad472";
      sha256 = "1j7hp8in4zsb66kk3w3r2596w6a21im6sp50jy7vm12n1vnph3cm";
    };
  }

  {
    goPackagePath = "github.com/Masterminds/semver";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/semver";
      rev = "c84ddcca87bf5a941b138dde832a7e20b0159ad8";
      sha256 = "1dcfdr018a0yszjpvr3wshvq9cc3kvy95l55si556p617wsn1wan";
    };
  }
  {
    goPackagePath = "github.com/appleboy/go-fcm";
    fetch = {
      type = "git";
      url = "https://github.com/appleboy/go-fcm";
      rev = "7856bec57549eadfe839c4eb4a54414a60818474";
      sha256 = "0m3lib9csbjxswi7hcdvrw5r1dkd4mxigari19hg1s83s5jgfp65";
    };
  }
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "3a771d992973f24aa725d07868b467d1ddfceafb";
      sha256 = "1l2lns4f5jabp61201sh88zf3b0q793w4zdgp9nll7mmfcxxjif3";
    };
  }
  {
    goPackagePath = "github.com/boombuler/barcode";
    fetch = {
      type = "git";
      url = "https://github.com/boombuler/barcode";
      rev = "34fff276c74eba9c3506f0c6f4064dbaa67d8da3";
      sha256 = "16y7cgwga9h8m7lad48qv9xa0xnm7rqfhscycz24mkvh8a97ip4r";
    };
  }
  {
    goPackagePath = "github.com/cozy/afero";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/afero";
      rev = "12b7d27decdd033919e7e01195e97dd3d9403ce8";
      sha256 = "0d5zf6gccs4jpvvflh3yz2ydj003ydcp4p1sp3xw8l91dlhvgbd5";
    };
  }
  {
    goPackagePath = "github.com/cozy/checkup";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/checkup";
      rev = "a2e2abe3abfb8a7d4a6a1637ab5823850721272e";
      sha256 = "0hyhbndi6vin5g496xd9w3abb0hz872jnggxbp12x6q732660gya";
    };
  }
  {
    goPackagePath = "github.com/cozy/echo";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/echo";
      rev = "6cf7445a14d19cc07049db7fb55b5ead6cc0782e";
      sha256 = "024xm2jk8y401g97zfcdsr3xjjlihd692cp88bacrw81p9fx7m6l";
    };
  }
  {
    goPackagePath = "github.com/cozy/go-git";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/go-git";
      rev = "69ddef0ce5d218d41bf18fee6a76dcc39a489999";
      sha256 = "034f2ajsms973kipxvxfs6p4cspaf14gy7cqmjf2mxpgrxh9hlyl";
    };
  }
  {
    goPackagePath = "github.com/cozy/goexif2";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/goexif2";
      rev = "830968571cff9f562ce76800527d4e192366a7be";
      sha256 = "03gjx6wpqfs64ljr7zljly4dimvyhsx7mg6biq7msyyjni3f40fp";
    };
  }
  {
    goPackagePath = "github.com/cozy/gomail";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/gomail";
      rev = "1395d9a6a6c08f7326b53c066358ab602ca10ed4";
      sha256 = "03hnm7zl992nv2ln1in5n44fl1qh0dkdxkj98djyal2qkh4d2459";
    };
  }
  {
    goPackagePath = "github.com/cozy/hermes";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/hermes";
      rev = "bccc9aa093b6ecfc4055fea72b3260392f377ba5";
      sha256 = "1bpjplyz8p2c0y01ifvdqrhys8nrpn8hqmhl4mfi16pw08wzxx13";
    };
  }
  {
    goPackagePath = "github.com/cozy/httpcache";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/httpcache";
      rev = "d3dc4988de664ed8089ccafd196d973304f29aa8";
      sha256 = "0n1f2fjrhfm5j39wsvgnmann4z3gmbdyfiv1szd9yixcwkgqzzr6";
    };
  }
  {
    goPackagePath = "github.com/cozy/swift";
    fetch = {
      type = "git";
      url = "https://github.com/cozy/swift";
      rev = "f1096d89805ee9f8f3bb0b3a64d5b76e96962daf";
      sha256 = "1wf3rpd3k3wlyrfkaijvhmpb1cgsh3fjfvsfkz9683y8kf0km06z";
    };
  }
  {
    goPackagePath = "github.com/cpuguy83/go-md2man";
    fetch = {
      type = "git";
      url = "https://github.com/cpuguy83/go-md2man";
      rev = "691ee98543af2f262f35fbb54bdd42f00b9b9cc5";
      sha256 = "1864g10y9n6ni0p1yqjhvwyjdh0lgxnf7dlb0c4njazdg5rppww9";
    };
  }
  {
    goPackagePath = "github.com/dgrijalva/jwt-go";
    fetch = {
      type = "git";
      url = "https://github.com/dgrijalva/jwt-go";
      rev = "3af4c746e1c248ee8491a3e0c6f7a9cd831e95f8";
      sha256 = "1a8sx166ck3shlxd7ijg84mh6w0qim8qgvi34iijsxrpl60kib07";
    };
  }
  {
    goPackagePath = "github.com/dhowden/tag";
    fetch = {
      type = "git";
      url = "https://github.com/dhowden/tag";
      rev = "a9f04c2798caa184ec116ff25e9a1a15e9b3f79a";
      sha256 = "1p1zqiynlix2qbdkqdszhgyk9v3j703yk6y16fdha79p3ydmxp3y";
    };
  }
  {
    goPackagePath = "github.com/dustin/go-humanize";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/go-humanize";
      rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e";
      sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3";
    };
  }
  {
    goPackagePath = "github.com/emersion/go-vcard";
    fetch = {
      type = "git";
      url = "https://github.com/emersion/go-vcard";
      rev = "8856043f13c54edb075ad5121315e5e89c3f5bfa";
      sha256 = "1dzw5awqbkf2nc09ynmn3zlylj4n1na96rziv5z8p42b1bmbklwk";
    };
  }
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "3f9d52f7176a6927daacff70a3e8d1dc2025c53e";
      sha256 = "165ww24x6ba47ji4j14mp3f006ksnmi53ws9280pgd2zcw91nbn8";
    };
  }
  {
    goPackagePath = "github.com/fsnotify/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/fsnotify/fsnotify";
      rev = "ccc981bf80385c528a65fbfdd49bf2d8da22aa23";
      sha256 = "0hcrfmiyx27izac3v0ii0qq2kfjvhr9ma1i79hrl6a6y2ayagzz7";
    };
  }
  {
    goPackagePath = "github.com/go-redis/redis";
    fetch = {
      type = "git";
      url = "https://github.com/go-redis/redis";
      rev = "473d039f0b771b88e3b942d3bdc61bf22766bab0";
      sha256 = "1vhjq61zwm7pjmzs5c641xy8y4vgp4axa4s1p1vbjhr329i2g641";
    };
  }
  {
    goPackagePath = "github.com/golang/gddo";
    fetch = {
      type = "git";
      url = "https://github.com/golang/gddo";
      rev = "9bd4a32950217197bb319565e843237cca7f85d2";
      sha256 = "0c97rilyq3kns4kcfzg8797bqapfllk8mbwh91h7salsqjjqv554";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "c823c79ea1570fb5ff454033735a8e68575d1d0f";
      sha256 = "0dm1ip7742qz2k1cr6ywy0av6mpcxd2kc4ayfqi8cxz3ai7zhbdr";
    };
  }
  {
    goPackagePath = "github.com/google/go-querystring";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-querystring";
      rev = "44c6ddd0a2342c386950e880b658017258da92fc";
      sha256 = "0xl12bqyvmn4xcnf8p9ksj9rmnr7s40pvppsdmy8n9bzw1db0iwz";
    };
  }
  {
    goPackagePath = "github.com/google/gops";
    fetch = {
      type = "git";
      url = "https://github.com/google/gops";
      rev = "9fda3b87c7b32caeeb2974e7cc2e71e60a597fdf";
      sha256 = "0rxpzbfis0cqpyxpnxpb1a4wcjz3gljr0s99q11673glz2jan4c6";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "7c8e298727d149d7c329b4dec7e94e1932ac5c11";
      sha256 = "0d84bzjng0s9yq3jq7m8hzj0q7djkzyz1shnbsiazxibdaz768xh";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/errwrap";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/errwrap";
      rev = "8a6fb523712970c966eefc6b39ed2c5e74880354";
      sha256 = "0slfb6w3b61xz04r32bi0a1bygc82rjzhqkxj2si2074wynqnr1c";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-multierror";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-multierror";
      rev = "886a7fbe3eb1c874d46f623bfa70af45f425b3d1";
      sha256 = "00nyn8llqzbfm8aflr9kwsvpzi4kv8v45c141v88xskxp5xf6z49";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "65a6292f0157eff210d03ed1bf6c59b190b8b906";
      sha256 = "00qgmygfa4vgf9v3lpz4vp1ca1hcfcxnjqjrvp6z4jjklc8x4mqf";
    };
  }
  {
    goPackagePath = "github.com/howeyc/gopass";
    fetch = {
      type = "git";
      url = "https://github.com/howeyc/gopass";
      rev = "bf9dde6d0d2c004a008c27aaee91170c786f6db8";
      sha256 = "1jxzyfnqi0h1fzlsvlkn10bncic803bfhslyijcxk55mgh297g45";
    };
  }
  {
    goPackagePath = "github.com/imdario/mergo";
    fetch = {
      type = "git";
      url = "https://github.com/imdario/mergo";
      rev = "7c29201646fa3de8506f701213473dd407f19646";
      sha256 = "05ir0jj74w0yfi1lrhjd97v759in1dpsma64cgmbiqvyp6hfmmf8";
    };
  }
  {
    goPackagePath = "github.com/jaytaylor/html2text";
    fetch = {
      type = "git";
      url = "https://github.com/jaytaylor/html2text";
      rev = "57d518f124b0cf46ea2021f25a01396b3522e6fb";
      sha256 = "15g4sz71p7zfx50aqcbckd3h9ycya5mrdi5117r6znd39z8jby0v";
    };
  }
  {
    goPackagePath = "github.com/justincampbell/bigduration";
    fetch = {
      type = "git";
      url = "https://github.com/justincampbell/bigduration";
      rev = "e45bf03c06663920551bc3a33855ee0e53dac3c9";
      sha256 = "1fb483gklrsyip710jx5sdz6hr6z8yfz5r8rl66i8kgf2czx9qyw";
    };
  }
  {
    goPackagePath = "github.com/labstack/gommon";
    fetch = {
      type = "git";
      url = "https://github.com/labstack/gommon";
      rev = "82ef680aef5189b68682876cf70d09daa4ac0f51";
      sha256 = "123h8maf2wzxidlsadkn64qbkrj2gv86kfmd62yppdfkb48zkvaj";
    };
  }
  {
    goPackagePath = "github.com/leonelquinteros/gotext";
    fetch = {
      type = "git";
      url = "https://github.com/leonelquinteros/gotext";
      rev = "ff3209d1595982d3247353badd0cc01f2c0b722b";
      sha256 = "0wc5xi0n8yhd453qd8ar9rhqhhnabywqkz809qxcqq6m9xbcdzil";
    };
  }
  {
    goPackagePath = "github.com/magiconair/properties";
    fetch = {
      type = "git";
      url = "https://github.com/magiconair/properties";
      rev = "7757cc9fdb852f7579b24170bcacda2c7471bb6a";
      sha256 = "1v3b69834k0pp4q238s8srx2f0kgxdy8i6akxdanmhldm6ajs035";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "efa589957cd060542a26d2dd7832fd6a6c6c3ade";
      sha256 = "0kshi4hvm0ayrsxqxy0599iv81kryhd2fn9lwjyczpj593cq069r";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "3fb116b820352b7f0c281308a4d6250c22d94e27";
      sha256 = "084hplr4n4g5nvp70clljk428hc963460xz0ggcj3xdi4w7hhsvv";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c182affec369e30f25d3eb8cd8a478dee585ae7d";
      sha256 = "1xqsf9vpcrd4hp95rl6kgmjvkv1df4aicfw4l5vfcxcwxknfx2xs";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/mssola/user_agent";
    fetch = {
      type = "git";
      url = "https://github.com/mssola/user_agent";
      rev = "8b39990837709a42bf92e5f8bc8707a901c57338";
      sha256 = "0nvyq9z79cq6yss0zl6ww1b9sapn8v6i3w8p8z1s4q4b5wrs0b9c";
    };
  }
  {
    goPackagePath = "github.com/nightlyone/lockfile";
    fetch = {
      type = "git";
      url = "https://github.com/nightlyone/lockfile";
      rev = "0ad87eef1443f64d3d8c50da647e2b1552851124";
      sha256 = "19vfswcvdy937da7w6hap3wp83drj5a084sqszy8r2ph4fbkln41";
    };
  }
  {
    goPackagePath = "github.com/olekukonko/tablewriter";
    fetch = {
      type = "git";
      url = "https://github.com/olekukonko/tablewriter";
      rev = "e6d60cf7ba1f42d86d54cdf5508611c4aafb3970";
      sha256 = "0hh95glg7d2md185r03wn52j2r33jc4zil0qvcrs66ka7bdxi7vj";
    };
  }
  {
    goPackagePath = "github.com/oschwald/maxminddb-golang";
    fetch = {
      type = "git";
      url = "https://github.com/oschwald/maxminddb-golang";
      rev = "31672ba7a68affbd201a4c909a72a0484fb1a2f0";
      sha256 = "1zyl3nzxcky7vvwkifn1dnrgzrlkwfrkaixql0fzpsrvmp6lyg9l";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "27c6b39a135b7dc87a14afb068809132fb7a9a8f";
      sha256 = "13ldxh43xf4prmcrjzriz3gxpnijpqlzrgyhh7bnkj7lkhryfpk9";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "ffb6e22f01932bf7ac35e0bad9be11f01d1c8685";
      sha256 = "197j5vpv03131rflygl7ks9bqbsx0sydq4bykw2hq0p6kg3grqzz";
    };
  }
  {
    goPackagePath = "github.com/pquerna/otp";
    fetch = {
      type = "git";
      url = "https://github.com/pquerna/otp";
      rev = "be78767b3e392ce45ea73444451022a6fc32ad0d";
      sha256 = "0qlcka83sx49sjn4ry7mdj9yj17za534sa1cydchkd4whwwmripb";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "7190de1ef27a67a600698247a86db923cd5b8127";
      sha256 = "0g9fv4k62f3wic9z34nb0r3vxf3pb87p1dg921bcn3wxzks5k95i";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "fd36f4220a901265f90734c3183c5f0c91daa0b8";
      sha256 = "1bs5d72k361llflgl94c22n0w53j30rsfh84smgk8mbjbcmjsaa5";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "f866ba39776a736ba5d34760f5fae4ad74e63f2e";
      sha256 = "0j6c1ixqs84c7f0ycgkwdmvy32641i3y4rf2k6lybmkwslayikka";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "f8d8b3f739bd91a7c0462cb55235ef63c79c9abc";
      sha256 = "0pgwp030wbyh5df0fsgi2wiks9yszjcapffdnrcihxzdv1vifl41";
    };
  }
  {
    goPackagePath = "github.com/robfig/cron";
    fetch = {
      type = "git";
      url = "https://github.com/robfig/cron";
      rev = "b41be1df696709bb6395fe435af20370037c0b4c";
      sha256 = "0nv31m3940d9kf38lw2zs4hpj435bdi9mmim098rb3n4l07qrvva";
    };
  }
  {
    goPackagePath = "github.com/sergi/go-diff";
    fetch = {
      type = "git";
      url = "https://github.com/sergi/go-diff";
      rev = "da645544ed44df016359bd4c0e3dc60ee3a0da43";
      sha256 = "19ynrcv2infmai6pan5wwc61z5bp74zs9clwf2jdwx1ngi2f0rbm";
    };
  }
  {
    goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
    fetch = {
      type = "git";
      url = "https://github.com/shurcooL/sanitized_anchor_name";
      rev = "7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615";
      sha256 = "1gv9p2nr46z80dnfjsklc6zxbgk96349sdsxjz05f3z6wb6m5l8f";
    };
  }
  {
    goPackagePath = "github.com/sideshow/apns2";
    fetch = {
      type = "git";
      url = "https://github.com/sideshow/apns2";
      rev = "060d44b53d05502e715958efde28063cd0746dba";
      sha256 = "02mfqg6xy651935qgqzjb3bh21q6glf325ndx28vxf1g2b9y27a4";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "4ea4861398d99a2d05be29675c5b74caf7bea95e";
      sha256 = "1v65v7xpr2iqksxs2wz5amd4cf39l4z4rgqw9zijsrg6x0kyvicm";
    };
  }
  {
    goPackagePath = "github.com/spf13/afero";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/afero";
      rev = "f4711e4db9e9a1d3887343acb72b2bbfc2f686f5";
      sha256 = "14qqj0cz6a595vn4dp747vddx05fd77jdsyl85qjmf9baymaxlam";
    };
  }
  {
    goPackagePath = "github.com/spf13/cast";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cast";
      rev = "8c9545af88b134710ab1cd196795e7f2388358d7";
      sha256 = "0xq1ffqj8y8h7dcnm0m9lfrh0ga7pssnn2c1dnr09chqbpn4bdc5";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "7547e83b2d85fd1893c7d76916f67689d761fecb";
      sha256 = "0hf8ja243113hq6603hxr38ghcbix06vrmri9gqarsn6dwn4l4bv";
    };
  }
  {
    goPackagePath = "github.com/spf13/jwalterweatherman";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/jwalterweatherman";
      rev = "94f6ae3ed3bceceafa716478c5fbf8d29ca601a1";
      sha256 = "1ywmkwci5zyd88ijym6f30fj5c0k2yayxarkmnazf5ybljv50q7b";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
  {
    goPackagePath = "github.com/spf13/viper";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/viper";
      rev = "d104d259b3380cb653bb793756823c3c41b37b53";
      sha256 = "0vcn8cwpz25s1r0yfi69wl2lh70hi2l1vghxwhz6vnjvhyk2hh53";
    };
  }
  {
    goPackagePath = "github.com/src-d/gcfg";
    fetch = {
      type = "git";
      url = "https://github.com/src-d/gcfg";
      rev = "1ac3a1ac202429a54835fe8408a92880156b489d";
      sha256 = "044j95skmyrwjw5fwjk6ka32rjgsg0ar0mfp9np19sh1acwv4x4r";
    };
  }
  {
    goPackagePath = "github.com/ssor/bom";
    fetch = {
      type = "git";
      url = "https://github.com/ssor/bom";
      rev = "6386211fdfcf24c0bfbdaceafd02849ed9a8a509";
      sha256 = "09g5496ifwqxqclh2iw58plcwcz0sczlnxwqxzwmnl4shdl371ld";
    };
  }
  {
    goPackagePath = "github.com/valyala/fasttemplate";
    fetch = {
      type = "git";
      url = "https://github.com/valyala/fasttemplate";
      rev = "dcecefd839c4193db0d35b88ec65b4c12d360ab0";
      sha256 = "0kkxn0ad5a36533djh50n9l6wsylmnykridkm91dqlqbjirn7216";
    };
  }
  {
    goPackagePath = "go4.org";
    fetch = {
      type = "git";
      url = "https://github.com/go4org/go4";
      rev = "00e24f1b25994999399dee600cb8f35a45f519dc";
      sha256 = "09j3aq8iyv9d6r5ikjbkl6jcvaywf367jlndhxj836sjbaxqpa4z";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "193df9c0f06f8bb35fba505183eaf0acc0136505";
      sha256 = "0rs0dwgjk8zsjqln312sj0sfj1c08bpm46nk1jphch8jzh9kc03b";
    };
  }
  {
    goPackagePath = "golang.org/x/image";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/image";
      rev = "ef4a1470e0dc5915f2f5fa04a28eeab72c6936a4";
      sha256 = "1xivl4p9xwh9733a7pg1scy9d0zca5kgjng9mx0jxb8kb9paphis";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "65e2d4e15006aab9813ff8769e768bbf4bb667a0";
      sha256 = "0aqcmh0sp723d6hwgrv7pnrs4crns2ngr4x43jd4v985cbn455x7";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "99b60b757ec124ebb7d6b7e97f153b19c10ce163";
      sha256 = "119py9nia7957kf51gg9qvh34d18jb1a293zwfgvdf5inl1ja6y6";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "3b5209105503162ded1863c307ac66fec31120dd";
      sha256 = "1m8vc8bbsvghlfvzd8pwr2d6mbwcvq3rn6s4pa4gxj9cf8fmk4gn";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "e6919f6577db79269a6443b9dc46d18f2238fb5d";
      sha256 = "1p830sa7zqv4vzan3sn34qgfzc8466glv5ln2w6la96yw70wwky3";
    };
  }
  {
    goPackagePath = "gopkg.in/dgrijalva/jwt-go.v3";
    fetch = {
      type = "git";
      url = "https://gopkg.in/dgrijalva/jwt-go.v3";
      rev = "06ea1031745cb8b3dab3f6a236daf2b0aa468b7e";
      sha256 = "08m27vlms74pfy5z79w67f9lk9zkx6a9jd68k3c4msxy75ry36mp";
    };
  }
  {
    goPackagePath = "gopkg.in/leonelquinteros/gotext.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/leonelquinteros/gotext.v1";
      rev = "477ce49ddf8f201350f40fdb5ed80a65d155cc33";
      sha256 = "1q4w06plxhxy227q3vfjk7bq4x80nbskq5iigqrdgrmr09cd2b1z";
    };
  }
  {
    goPackagePath = "gopkg.in/russross/blackfriday.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/russross/blackfriday.v2";
      rev = "d3b5b032dc8e8927d31a5071b56e14c89f045135";
      sha256 = "0nlz7isdd4rgnwzs68499hlwicxz34j2k2a0b8jy0y7ycd2bcr5j";
    };
  }
  {
    goPackagePath = "gopkg.in/src-d/go-billy.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/src-d/go-billy.v2";
      rev = "52497601f113730d14baa00453674376fca22f22";
      sha256 = "1plwr1hyib6m3cmv0b3gqygm2vl7fd8zxf69imvhc7ac4x1j3n0v";
    };
  }
  {
    goPackagePath = "gopkg.in/warnings.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/warnings.v0";
      rev = "ec4a0fea49c7b46c2aeb0b51aac55779c607e52b";
      sha256 = "1kzj50jn708cingn7a13c2wdlzs6qv89dr2h4zj8d09647vlnd81";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
