# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.tmpOnTmpfs = true;

  boot.loader = {
    systemd-boot.enable = true;
    grub.device = "/dev/nvme0n1p3";
    efi.canTouchEfiVariables = true;
  };

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6db074b2-b1ef-478a-b070-f6ff890031a4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/6d076e27-f270-4178-8734-6d86f2ceaa69";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C3F0-310C";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/2def9120-3175-40ce-aa18-132885daa181"; }];

  console.keyMap = "fr";
  services.xserver.layout = "fr";
  services.xserver.xkbOptions = "compose:ralt";
  services.xserver.dpi = 180;

  services.xserver.libinput.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
